### ISSUE TITLE
Sync (mirror) doesn't delete destination recursive

### ISSUE THREAD

**Issue by FiSHYsolutions** [PortableApps/Toucan#22] opened 2018-09-10 15:00 UTC
I try to use sync (mirror) but it doesn't work as expected.

Summary from help: "_Mirror -> Copy every file in the source directory to the destination directory, and delete every file in the destination directory that is not in the source directory._"

Ok, let's go. We have a testfolder "Source" with some content and an empty folder "Destination". At first we mirror-sync from source to destination:

![1](https://user-images.githubusercontent.com/222112/45304537-9648dc00-b518-11e8-8768-f9e57bbbae4b.JPG)
![1_log](https://user-images.githubusercontent.com/222112/45304538-9648dc00-b518-11e8-8361-a36256258b42.JPG)

Everything looks fine.
Now i delete "Folder A" from source (using Windows Explorer), hit refresh in Toucan and it shows the source as it is (without "Folder A").

![2](https://user-images.githubusercontent.com/222112/45304539-9648dc00-b518-11e8-9888-441b442298e2.JPG)

So far so good, i hit the "Run"-Button to mirror-sync again from source to destination and i expect the complete removal of "Folder A" (and it's content) in destination. 

![2_log](https://user-images.githubusercontent.com/222112/45304540-9648dc00-b518-11e8-8f5d-7de280197013.JPG)

And here something went wrong. At first: the log shows "Removed ... file a.txt" twice. Why? There was only one file. The log also says "Folder A.1" and "Folder A" were removed, but after refreshing Toucan we find the subdirectory untouched (and we can also access it with Explorer or something else). So they are not deleted:

![3](https://user-images.githubusercontent.com/222112/45304541-9648dc00-b518-11e8-9a83-2dc393dd51da.JPG)

**Comment by alex-ter** [comment] 2019-01-05 19:53
So the duplicate "Removed file" entries are due to the duplicated logging in the code ([here](https://github.com/PortableApps/Toucan/blob/master/sync/syncjob.cpp#L260) and [here](https://github.com/PortableApps/Toucan/blob/master/sync/syncjob.cpp#L286)).

The non-removal of the directory is most probably because of the fact that the files inside it are not removed - apparently the code uses a directory deletion function that doesn't remove non-empty dirs and looks like the error handling there is incorrect ([here](https://github.com/PortableApps/Toucan/blob/master/sync/syncjob.cpp#L270))

Now why the file is not actually removed is hard to say based on the information I have - the code looks okay (except that apparently the error handling is also not doing the job properly - the file is not removed, but it thinks it is). Could you please check if the file in question is by chance set as read-only? If so, please try setting the "Ignore Read-Only" option under "Other" - I see you have it unchecked. Or if that doesn't work - remove the read-only flag in the Windows Explorer directly.

**Comment by FiSHYsolutions** [comment] 2019-01-05 20:05
nope, the file is not flagged "read only". it's a very simple txt-file, created seconds before the test i did to report this behaviour and IMHO it should be very easy to re-enact it. i never did any special shit. it's an absolute plain usage of toucan's sync and the described problem appears with every directories i try to re-sync. target-data is not deleted recursive.

**Comment by alex-ter** [comment] 2019-01-13 00:53
Ok, thanks for information. Let me see if I can reproduce this.

**Comment by alex-ter** [comment] 2019-02-09 14:31
Ok, I can't seem to reproduce this. I've however done some error handling cleanup, fixed the duplicate logging for file removal and used a different function for dir removal (`wxRmdir()` vs current `wxRmDir()`), which I think was a typo in the first place. The Toucan binary with the new approach is attached - could you please try it out, using exactly the same scenario you used orignally, and report back? If not fixing it, it should at least be properly reporting deletion statuses, which should help us move forward with investigation. 

To make it easier to test - just temporarily replace your current Toucan binary. As there are no other changes, this file is fully compatible with your current rules/variables/jobs files. However it's always wise to create a backup copy of your full Portableapps setup just in case.

Specifically:
1. Rename `<your portableapps install dir>\PortableApps\Toucan\App\Toucan\toucan.exe` to `toucan.exe.orig`
1. Unpack the attached zip and copy `toucan.exe` into the same dir
1. Run Toucan and execute the scenario

[toucan.zip](https://github.com/PortableApps/Toucan/files/2847895/toucan.zip)

**Comment by FiSHYsolutions** [comment] 2019-03-26 11:08
Issue isn't solved.

- Step 1) sync (to empty destination) works fine
- Step 2) delete "Folder A" in source
- Step 3) sync again, but "Folder A" isn't deleted in destination

![Toucan_v3 1 6_failed](https://user-images.githubusercontent.com/222112/54992504-c0974e00-4fbf-11e9-9d7b-700f6e0121d3.JPG)

The log starts with an error which is true (but i didn't understand the missing backslash between "Folder A.1" and "file a.1.txt", maybe that's the issue?). But "Folder A\file a.txt" were deleted successfully!

**Comment by alex-ter** [comment] 2019-07-27 19:36
Okay, as they say: "better late than never", right? :smiley:

I was finally able to find the time to look at this further, found the root cause, reproduced and fixed it. The reason was that with nested dirs [the recursive call to dir deletion subroutine](https://github.com/PortableApps/Toucan/blob/master/sync/syncjob.cpp#L256) passed the path as a file (not dir) name, which caused that result you observed with lack of the path separator. That caused the file deletion to fail inside the dir, so the dir deletion failed as well.

I'm pretty sure it's fixed now as I can no longer reproduce it (after having the same result as you with the original code), but just to make sure - here's the test build, if you're still up to that, could you please check it out according to the instructions from [my earlier comment](https://github.com/PortableApps/Toucan/issues/22#issuecomment-462049260) and tell me if it fixes it for you?

[toucan.zip](https://github.com/PortableApps/Toucan/files/3438521/toucan.zip)

**Comment by FiSHYsolutions** [comment] 2019-08-02 12:47
Problem solved!
I used a new fresh toucan v3.1.5 (from PortableApps), replaced App\Toucan\toucan.exe, and everything works as expected. Tried it with Windows 7 Build 7601 SP1 x64 and Windows 10 Pro x64 Version 1809 (the Toucan-log said "NT 6.2 build 9200", thats maybe incorrect?).

Thank you very much!

**Comment by alex-ter** [comment] 2019-08-05 18:21
Great, thank you for confirmation. I'll prepare a release hopefully some time this week.

**Closed as completed** 2019-08-13 12:59 UTC
Labels: bug
