### ISSUE TITLE
[Bug] there are no incremental differential files for differential Backup.

### ISSUE THREAD

**Issue by gary-gabriel** [PortableApps/Toucan#30] opened 2020-04-01 20:03 UTC
Ref: [Bug] reported from PortableApps on Apr. 1, 2020.

Thanks for the prompt response.

Toucan has served well in the past and thanks for the update. However probably since this update there is a bug in the Differential Backup. Assuming that the past behavior that changed files are backed up up in an archive named after the date and time is current.
	
Differential backup does not add incremental, differential files. In an incremental differential backup Toucan adds the incremental differential files for the new changes. However since at least Jan. 2020 Toucan only generates the file 'BaseFile.7z '. After successfully running a Backup set as Differential 7-Zip for one folder, no differential dated file is generated. It is certain that there were changed files in the backup. That means that the diff algorithm did not detect the changes in the files. 'BaseFile.7z ' remains the only file generated.
	
system details (Window 10 pro, 64-bit, install path: F:\PortableApps\Toucan, current update Toucan 3.1.7).
	
Toucan Settings 
- Type: 'Differential'
- Format: '7-Zip'
- Compression Level: 'Default'
- Other: 'Run'
- Computer Files to Backup: one folder is selected
- Backup Location: 'F:\DELL5NET\imc_nb_stages\Stages\ArcStore\ArcStore_Temp\WD04_DELL5NET_Toucan_Stages_ArcStore_temp_Stages-diff_2020D01'
An external USB drive folder is set as the location.

Confirming test on Apr. 1, 2020. The result of running the above backup is only the file F:\DELL5NET\imc_nb_stages\Stages\ArcStore\ArcStore_Temp\WD04_DELL5NET_Toucan_Stages_ArcStore_temp_Stages-diff_2020D01\BaseFile.7z 
	
Otherwise Toucan has been a very reliable backup solution in the last years and very much appreciated.
	
Thank you for your attention - Gary Gabriel

**Comment by alex-ter** [comment] 2020-05-01 14:41
I think this is a duplicate of #28, which I've fixed in the git, but haven't got time or enough motivation (in a form of requests) to actually release. As mentioned in the readme, this one is not in the maintenance mode, so I'm not actively working on Toucan.

Anyway, let me actually perform a release so that you can at least test and see if the fix for #28 fixes it for you as well.

**Comment by alex-ter** [comment] 2020-05-01 16:35
The 3.1.8 with the fix I mentioned is out: https://github.com/PortableApps/Toucan/releases/tag/3.1.8.1. Feel free to give it a try.

**Comment by riksoft** [comment] 2020-07-01 09:04
I tried the 3.1.7 from portableapps just to see if there were any improvements on my older 3.0.4 that has 1 single problem: it crashes clicking "Rules" button.

I'm now back on the older version because with 3.1.7:
1) Differential backup is not working at all.
It creates a 7z inside a 7z. Even setting compression=none, it makes a 7z inside a 7z.
Moreover, the archive is left locked.

2) .zip is not supported anymore for differential, differently from previous versions.

**Comment by alex-ter** [comment] 2020-07-25 13:06
@riksoft, as you can see from the discussion here, it's the 3.1.*8* that has the fix, 3.1.7 doesn't. Feel free to give 3.1.8 a try to see if it fixes it (back up your data in advance just in case).

**Comment by alex-ter** [comment] 2020-08-04 18:31
Now that 3.1.8 was released not only on GH but via PortableApps, I believe you should have this fixed. If not - please report back and I'll take a look.

**Closed as completed by alex-ter** 2020-08-04 18:31 UTC
Labels: duplicate
